title: TARDIS
baseURL: https://tardis-sn.github.io/preview/ # Remove "preview/" when ready to publish publicly
params:
  base_font: nunito-sans
  palette: blue
  header:
    logo_img: images/tardis-logo-2.svg
    logo_img_alt: Logo
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Documentation
        url: /documentation
        style: link
      - label: Team
        url: /team
        style: link
      - label: Research
        url: /research
        style: link
      - label: Credits
        url: /credits
        style: link
      - label: News
        url: /news
        style: link #primary is another style available
  footer:
    sections:
      - type: footer_text
        image: images/tardis-banner-2.svg
        image_url: /
        image_alt: Footer logo
        title: TARDIS-SN
      - type: footer_nav
        title: Company
        nav_links:
          - label: About Us
            url: /about
            style: link
          - label: Blog
            url: /blog
            style: link
          - label: Sign Up
            url: /signup
            style: link
          - label: Contact
            url: /contact
            style: link
      - type: footer_nav
        title: Community
        nav_links:
          - label: Twitter
            url: "https://twitter.com/tardis_sn"
            style: link
            has_icon: true
            icon: twitter
            icon_position: left
          - label: GitHub
            url: "https://github.com/tardis-sn"
            style: link
            has_icon: true
            icon: github
            icon_position: left
          - label: Gitter
            url: "https://gitter.im/tardis-sn/tardis"
            style: link
            has_icon: true
            icon: images/icons8-gitter-50.svg
            icon_position: left
      - type: footer_text
        title: Powered by NUMFOCUS
        image: images/Numfocus_stamp.png
    has_nav: true
    nav_links:
      - label: Terms of Service
        url: /terms-of-service
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=azimuth&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>.
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
